### PR TITLE
Add module for bucket lifecycle rules

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
Add new module to manage object bucket lifecycle rules

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
purefb_lifecycle.py

##### ADDITIONAL INFORMATION
SDK 1.10-RC3 does not support `enabled` option, so in testing do not try to disable a rule.
This will be fixed in the GA realse of the SDK

### CODE REVIEW

**Review by dnix101 — CHANGES_REQUESTED** [review]
`prefix` seems to be required for creation of lifecycle policy, where it shouldn't be required.

Also creating a lifecycle policy with `enabled: false` creates the policy with enabled: true and returns an error.

**Comment by sdodsley** [comment]
@dnix101 you didn't read the PR Summary did you???

**Comment by dnix101** [comment]
Uuhhhmmm, nope didn't...

**Comment by sdodsley** [comment]
@dnix101 I just fixed the `prefix` thing.

**Comment by dnix101** [comment]
👍👍👍

**Review by dnix101 — APPROVED** [review]
shipit

**Pull request merged**
