### PR TITLE
New module for object store user access policies

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
New module to manage object store user access policies
Requires Purity//FB 3.2+
`state: show` provides list of all available access policies, If an `account/name` is provide list the current access policies assigned to that user. 

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
purefb_userpolicy.py

### CODE REVIEW

**Review by rdeenik — DISMISSED** [review]
lgtm, one possible suggestion is for the `present` and `absent` states to return the new list of policies as output. That can sometimes saves a second call to the module to show new list.

**Comment by sdodsley** [comment]
@rdeenik Thel ist is to get all the available policies. `present1` and `absent` are specifically for the account/user.
Currently, there is no way to create or delete actual access policies.

**Comment by rdeenik** [comment]
I actually ment return the list of policies that are attached to the user after adding/removing a policy to the user. Not adding new policies themselves.

**Comment by sdodsley** [comment]
@rdeenik OK - I can probably do that

**Review by rdeenik — APPROVED** [review]
Awesome, shipit!

**Pull request merged**
